"""Build a portable single-file version of the pre presentation page.

The generated HTML embeds the presentation CSS, JavaScript, JSON snapshots, and
PNG chart assets so it can be opened directly from disk on another computer.
"""

from __future__ import annotations

import argparse
import base64
import json
import mimetypes
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PUBLIC_DIR = REPO_ROOT / "frontend" / "public"
PRE_DIR = PUBLIC_DIR / "pre"
DEMO_SHOWCASE_DIR = PUBLIC_DIR / "demo_showcase"

DEFAULT_INDEX = PRE_DIR / "index.html"
DEFAULT_CSS = PRE_DIR / "presentation.css"
DEFAULT_JS = PRE_DIR / "presentation.js"
DEFAULT_OUTPUT = PRE_DIR / "standalone.html"

DATA_FILES = {
    "/demo_showcase/demo_snapshot.json": DEMO_SHOWCASE_DIR / "demo_snapshot.json",
    "/demo_showcase/exploratory_dl_summary.json": DEMO_SHOWCASE_DIR
    / "exploratory_dl_summary.json",
    "/demo_showcase/report/summary.json": DEMO_SHOWCASE_DIR / "report" / "summary.json",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def escape_script_json(payload: object) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace(
        "</", "<\\/"
    )


def load_embedded_data() -> dict[str, object]:
    data: dict[str, object] = {}
    for public_url, path in DATA_FILES.items():
        data[public_url] = json.loads(read_text(path))
    return data


def encode_asset(path: Path) -> str:
    media_type = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{media_type};base64,{encoded}"


def load_embedded_assets() -> dict[str, str]:
    assets: dict[str, str] = {}
    for path in sorted((DEMO_SHOWCASE_DIR / "assets").glob("*")):
        if not path.is_file():
            continue
        public_path = f"demo_showcase/assets/{path.name}"
        assets[public_path] = encode_asset(path)
    return assets


def patch_javascript(script: str) -> str:
    read_json_source = """  async function readJson(url) {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to load ${url}: ${response.status}`);
    }
    return response.json();
  }"""
    read_json_replacement = """  async function readJson(url) {
    const embeddedData = window.__PRESENTATION_EMBEDDED_DATA__ || {};
    if (!Object.prototype.hasOwnProperty.call(embeddedData, url)) {
      throw new Error(`Embedded presentation data unavailable for ${url}`);
    }
    if (typeof structuredClone === "function") {
      return structuredClone(embeddedData[url]);
    }
    return JSON.parse(JSON.stringify(embeddedData[url]));
  }"""

    asset_url_source = """  function toPublicAssetUrl(path) {
    if (!path) {
      return "";
    }
    return path.startsWith("/") ? path : `/${path}`;
  }"""
    asset_url_replacement = """  function toPublicAssetUrl(path) {
    if (!path) {
      return "";
    }
    if (/^(data:|blob:|https?:|mailto:)/i.test(path)) {
      return path;
    }
    const embeddedAssets = window.__PRESENTATION_EMBEDDED_ASSETS__ || {};
    const normalizedPath = path.replace(/^\\/+/, "");
    if (Object.prototype.hasOwnProperty.call(embeddedAssets, path)) {
      return embeddedAssets[path];
    }
    if (Object.prototype.hasOwnProperty.call(embeddedAssets, normalizedPath)) {
      return embeddedAssets[normalizedPath];
    }
    return path.startsWith("/") ? path : `/${path}`;
  }"""

    for source, replacement in (
        (read_json_source, read_json_replacement),
        (asset_url_source, asset_url_replacement),
    ):
        if source not in script:
            raise RuntimeError("Could not patch presentation.js; source shape changed.")
        script = script.replace(source, replacement)
    return script


def build_standalone_html(
    index_path: Path = DEFAULT_INDEX,
    css_path: Path = DEFAULT_CSS,
    js_path: Path = DEFAULT_JS,
) -> str:
    html = read_text(index_path)
    css = read_text(css_path)
    script = patch_javascript(read_text(js_path))
    embedded_data = load_embedded_data()
    embedded_assets = load_embedded_assets()

    data_bootstrap = "\n".join(
        [
            "window.__PRESENTATION_EMBEDDED_DATA__ = "
            f"{escape_script_json(embedded_data)};",
            "window.__PRESENTATION_EMBEDDED_ASSETS__ = "
            f"{escape_script_json(embedded_assets)};",
        ]
    )

    css_link = '    <link rel="stylesheet" href="/pre/presentation.css?v=11" />'
    css_block = f"    <style>\n{css}\n    </style>"
    script_tag = '    <script src="/pre/presentation.js?v=11"></script>'
    script_block = (
        "    <script>\n"
        "/* Generated by scripts/demo/build_standalone_presentation.py. */\n"
        f"{data_bootstrap}\n"
        f"{script}\n"
        "    </script>"
    )

    if css_link not in html:
        raise RuntimeError("Could not find presentation CSS link in index.html.")
    if script_tag not in html:
        raise RuntimeError("Could not find presentation JS script tag in index.html.")
    html = html.replace(css_link, css_block)
    html = html.replace(script_tag, script_block)
    return html


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build frontend/public/pre/standalone.html for portable demos."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output HTML path. Defaults to frontend/public/pre/standalone.html.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = args.output
    if not output_path.is_absolute():
        output_path = REPO_ROOT / output_path
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_standalone_html(), encoding="utf-8", newline="\n")
    print(f"Wrote portable presentation HTML: {output_path}")


if __name__ == "__main__":
    main()
